/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SizeVariants, ThemePalette } from "./shared/theme/theme.types";
import { ButtonStyle } from "./components/yoo-button/yoo-button.types";
import { IconAnimation, IconName, IconSize } from "./components/yoo-icon/yoo-icon.types";
export { SizeVariants, ThemePalette } from "./shared/theme/theme.types";
export { ButtonStyle } from "./components/yoo-button/yoo-button.types";
export { IconAnimation, IconName, IconSize } from "./components/yoo-icon/yoo-icon.types";
export namespace Components {
    interface YooButton {
        "block": boolean;
        "color": ThemePalette;
        "disabled"?: boolean;
        "iconAnimation"?: any;
        "iconLeft"?: string | undefined;
        "iconRight"?: string | undefined;
        "label"?: string | undefined;
        "size": SizeVariants;
        "variant": ButtonStyle;
    }
    interface YooIcon {
        "animation"?: IconAnimation;
        "background"?: string;
        "color": string;
        "icon": IconName;
        "size": number | IconSize;
    }
    interface YooInputGroup {
        "condition": boolean;
        "inputName": string;
        "isRequired": boolean;
        "label": string;
        "placeholder"?: string;
        "trailingIcon": boolean;
    }
}
declare global {
    interface HTMLYooButtonElement extends Components.YooButton, HTMLStencilElement {
    }
    var HTMLYooButtonElement: {
        prototype: HTMLYooButtonElement;
        new (): HTMLYooButtonElement;
    };
    interface HTMLYooIconElement extends Components.YooIcon, HTMLStencilElement {
    }
    var HTMLYooIconElement: {
        prototype: HTMLYooIconElement;
        new (): HTMLYooIconElement;
    };
    interface HTMLYooInputGroupElement extends Components.YooInputGroup, HTMLStencilElement {
    }
    var HTMLYooInputGroupElement: {
        prototype: HTMLYooInputGroupElement;
        new (): HTMLYooInputGroupElement;
    };
    interface HTMLElementTagNameMap {
        "yoo-button": HTMLYooButtonElement;
        "yoo-icon": HTMLYooIconElement;
        "yoo-input-group": HTMLYooInputGroupElement;
    }
}
declare namespace LocalJSX {
    interface YooButton {
        "block"?: boolean;
        "color"?: ThemePalette;
        "disabled"?: boolean;
        "iconAnimation"?: any;
        "iconLeft"?: string | undefined;
        "iconRight"?: string | undefined;
        "label"?: string | undefined;
        "size"?: SizeVariants;
        "variant"?: ButtonStyle;
    }
    interface YooIcon {
        "animation"?: IconAnimation;
        "background"?: string;
        "color"?: string;
        "icon": IconName;
        "size"?: number | IconSize;
    }
    interface YooInputGroup {
        "condition"?: boolean;
        "inputName"?: string;
        "isRequired"?: boolean;
        "label"?: string;
        "placeholder"?: string;
        "trailingIcon"?: boolean;
    }
    interface IntrinsicElements {
        "yoo-button": YooButton;
        "yoo-icon": YooIcon;
        "yoo-input-group": YooInputGroup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "yoo-button": LocalJSX.YooButton & JSXBase.HTMLAttributes<HTMLYooButtonElement>;
            "yoo-icon": LocalJSX.YooIcon & JSXBase.HTMLAttributes<HTMLYooIconElement>;
            "yoo-input-group": LocalJSX.YooInputGroup & JSXBase.HTMLAttributes<HTMLYooInputGroupElement>;
        }
    }
}
